### ISSUE TITLE
Auto-instrumented Flask API throws bad requests on routes

### ISSUE THREAD

**Issue by ericnograles** [honeycombio/honeycomb-opentelemetry-python#138]
## Versions

```
honeycomb-opentelemetry==0.2.1b0
opentelemetry-api==1.17.0
opentelemetry-exporter-otlp==1.17.0
opentelemetry-exporter-otlp-proto-grpc==1.17.0
opentelemetry-exporter-otlp-proto-http==1.17.0
opentelemetry-instrumentation==0.38b0
opentelemetry-instrumentation-aiohttp-client==0.38b0
opentelemetry-instrumentation-aws-lambda==0.38b0
opentelemetry-instrumentation-dbapi==0.38b0
opentelemetry-instrumentation-flask==0.38b0
opentelemetry-instrumentation-grpc==0.38b0
opentelemetry-instrumentation-jinja2==0.38b0
opentelemetry-instrumentation-logging==0.38b0
opentelemetry-instrumentation-requests==0.38b0
opentelemetry-instrumentation-sqlalchemy==0.38b0
opentelemetry-instrumentation-sqlite3==0.38b0
opentelemetry-instrumentation-urllib==0.38b0
opentelemetry-instrumentation-urllib3==0.38b0
opentelemetry-instrumentation-wsgi==0.38b0
opentelemetry-propagator-aws-xray==1.0.1
opentelemetry-proto==1.17.0
opentelemetry-sdk==1.17.0
opentelemetry-semantic-conventions==0.38b0
opentelemetry-util-http==0.38b0
```

## Steps to Reproduce

- Execute `FLASK_DEBUG=false opentelemetry-instrument python application.py`
- Issue a GET on `http://127.0.0.1:5000/user`
- Observe `code 400, message Bad request version ('À\x13À')` error in Flask

![image](https://github.com/honeycombio/honeycomb-opentelemetry-python/assets/6023705/56042fc9-a378-46d3-a667-da2e8784d9ea)

## Additional Context

Hi there,

Upon successful auto-instrumentation of my Python Flask API, for some reason all my routes now return a code 400 with a cryptic "bad request version". See screenshot above for additional context.

Note that running the Flask API directly with just `python application.py`, the route works as intended.

Here is the code for the route, it's rather simple:

```
def get(self):
        query = db.select(UserInfo).order_by(UserInfo.created_at)
        users = db.session.execute(query).scalars().all()
        return jsonify(users)
```

How do I troubleshoot this?

Thank you!

**Comment by JamieDanielson** [comment]
Hi @ericnograles, thanks (again!) for providing all the details and logging output!

 🤔 I tried this out and seem able to reproduce this error with or without instrumentation... if the protocol for the endpoint I hit is `https` instead of `http` and I'm using localhost. I'm noticing in your logging output it shows `"GET /user HTTP/1.1" 302` which is a redirect, and the User Agent looks to be a browser (Mac / Chrome). I'm wondering if maybe you typed in `http://127.0.0.1:5000/user` and the browser redirected to `https://127.0.0.1:5000/user` (because chrome tries to use https by default).

In my local testing, I used a `curl` command instead of a browser (I don't have a frontend setup) and noticed the same error on the server side terminal, and an SSL error in the client terminal `...tlsv1 alert protocol version` when I did `curl https://localhost:5000/users`.

```sh
INFO:werkzeug:127.0.0.1 - - [26/May/2023 15:21:11] "GET /users HTTP/1.1" 200 -
DEBUG:urllib3.connectionpool:[https://api.honeycomb.io:443](https://api.honeycomb.io/) "POST /v1/traces HTTP/1.1" 200 0
ERROR:werkzeug:127.0.0.1 - - [26/May/2023 15:21:16] code 400, message Bad request version ('\x86\x8bÌRËÀS¥¢HÏ¢ï\x9aÃ«å-\x04¢9
```

Could you try to rule that out by double-checking this again and ensuring the browser isn't redirecting you to "https"?

**Comment by ericnograles** [comment]
@JamieDanielson brilliant, that was it. I launched Flask in an ad-hoc SSL context and it works, thanks so much! Closing the issue.
