### ISSUE TITLE
Can't use Honeycomb Otel package with Python 3.12 in PyCharm's Python debugger - 'ValueError - wrapper has not been initialized'

### ISSUE THREAD

**Issue by kmcquade** [honeycombio/honeycomb-opentelemetry-python#187]
**Versions**
* Python 3.12 (works for 3.11 but breaks for 3.12)
* Using the latest commit from main in this repository

**Steps to reproduce**

I put together a 2 minute Loom video to quickly explain and demo. I also used the "Hello world" example in this repository to keep the example as simple as possible. https://www.loom.com/share/920edff709e149bc8fd14ec45fc9b130

This example requires Python 3.12, 3.11, and Pycharm to be installed.

1. Download the project and open the hello world example in Pycharm
```bash
git clone https://github.com/honeycombio/honeycomb-opentelemetry-python.git
cd examples/hello-world
# Enter Pycharm if installed
pycharm .
```
2. Accept the prompts to set up Poetry 3.12 for the project.
3. Hit "Run" and observe it works. 
4. Hit "Debug" and observe the failure.
5. Delete the Python interpreter for the project and start a new one, using Python 3.11.
6. Hit "Run" and observe it works.
7. Hit "Debug" and observe it works.

I am not sure how to work around this. Dropping to 3.11 isn't an option for this project... I will try to instrument with the OpenTelemetry package instead of this one in the meantime.

Hope this helps! Would love to know of a workaround/solution. Thanks again for the great product!

**Comment by kmcquade** [comment]
Somewhat related: I noticed that the CircleCI config isn't testing for Python 3.11. Not sure if that would have uncovered the problem, but might be worth adding that. https://github.com/honeycombio/honeycomb-opentelemetry-python/blob/02cc4bf6642c5a3f35f7b6479243929d865e9916/.circleci/config.yml#L23

**Comment by MikeGoldsmith** [comment]
Hey @kmcquade - thanks for creating the detailed issue. We'll take a look to see what we can find out and options we have.

**Comment by JamieDanielson** [comment]
Thanks for the detailed report @kmcquade !

For some reason I am having trouble reproducing, though I do have a thought about what may be in our code that is causing this error that doesn't exist upstream. I will keep working on that. I am also able to run this app in 3.12 so I wonder if that issue is more about testing 3.12 and/or some specific areas of code that are not guaranteed to work yet on 3.12. Notably the tests don't seem to finish installing packages in our CI if I use version 3.12 so that looks to be a bit more work to dig into at the moment, but that can be done separately from trying to resolve your issue here.

In the meantime, I have found [this issue for PyCharm ](https://youtrack.jetbrains.com/issue/PY-62322/Breakpoints-dont-work-with-Python-3.12) and the suggestion for a current workaround is to go to "Find Action" -> "Registry" -> type "debug" -> disable "`python.debug.low.impact.monitoring.api`". Is that an option that you can try to see if it gets around the current situation?

**Comment by JamieDanielson** [comment]
Ah, okay I saw some notes about fixes that may exist in newer versions of PyCharm. Notably, I was using PyCharm 2024.1, and it looks like your version is PyCharm 2023.3. I was able to [find a download of PyCharm 2023.3](https://www.jetbrains.com/pycharm/download/other.html) and am able to reproduce this now.

@kmcquade Is upgrading PyCharm an option for you?

**Comment by kmcquade** [comment]
Hi, yes this fixed it! Thank you :)
